version: '3.9'
services:
  # angular: 
  #   depends_on:
  #     - node
  #   build: 
  #     context: ./CLIENT-WEB-ANGULAR
  #     dockerfile: Dockerfile
  #   container_name: angular-client-container
  #   ports:
  #     - '8081:80'
  #   volumes:
  #     - ./CLIENT-WEB-ANGULAR:/usr/src/app
  #     - /usr/src/app/node_modules 
  #   restart: always
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     - mongo-network
  mongodb: 
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  mongo_seed:
    build: ./mongo_seed
    depends_on:
      - mongodb
  app:
    depends_on:
      - mongodb
    build: 
      context: ./SERVER-EXPRESS-JS
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: